[font]
normal = { family = "Iosevka", style = "Regular" }
size = 18

[window]
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[colors.primary]
background = "#1c1c1e"
foreground = "#eeedde"

[colors.normal]
black   = "#242424" # 0
red     = "#d17067" # 1
green   = "#90a959" # 2
yellow  = "#e7b67d" # 3
blue    = "#739cd9" # 4
magenta = "#aa759f" # 5
cyan    = "#75b5aa" # 6
white   = "#9d9d9d" # 7

[colors.bright]
black   = "#6c6c6c" # 8
red     = "#ff9e9b" # 9
green   = "#aac474" # 10
yellow  = "#feca88" # 11
blue    = "#99c9ee" # 12
magenta = "#c28cb8" # 13
cyan    = "#93d3c3" # 14
white   = "#f8f8f8" # 15
